[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
toml = "0.5"
serde = { version = "1", features = ["derive"] }
anyhow = "1"

[profile.release]
debug = true
